name: $(date:yyyymmdd)$(rev:.rr) #20191209.00

trigger:    # trigger the build when there is new code on master
  - master 

stages:
  - stage: compile 
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-1804
        steps:
          - script: |
              dotnet build 3_devops/Devops.sln
