name: $(date:yyyyMMdd)$(rev:.rr) #20191209.00

trigger:    # trigger the build when there is new code on master
  - master 

stages:
  - stage: compile 
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              dotnet build 3_devops/Devops.sln
  - stage: test
    jobs:
    - job: aspnet_test
      pool:
        vmImage: ubuntu-18.04
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: test
            projects: 3_devops/Devops.sln
            arguments: '--collect:"XPlat Code Coverage"'
        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: cobertura
            summaryFileLocation: '**/coverage.cobertura.xml'
  - stage: analyze
    jobs:
    - job:
      pool:
        vmImage: ubuntu-18.04
      steps:
        - task: DotnetGlobalToolInstaller@0
          inputs:
            name: 'dotnet-sonarscanner'
        - script: |
            dotnet sonarscanner begin /k:devops-rlguzman /d:sonar.login=$(SONAR_LOGIN) /o:rlguzman
            dotnet build 3_devops/Devops.sln
            dotnet test 3_devops/Devops.sln
            dotnet sonarscanner end /d:sonar-login=$(SONAR_LOGIN)
          env:
            SONAR_LOGIN: $(SONAR_LOGIN)
  - stage: pack
    jobs:
    - job:
      pool:
        vmImage: ubuntu-18.04
      steps:
        - script: docker image build -f 3_devops/dockerfile -t rlguzman/devops:$BUILD_NAME
          env:
            BUILD_NAME: $(Build.DefinitionName)
        - script: docker login -username $DOCKER_USER --password $DOCKER_TOKEN
          env:
            DOCKER_TOKEN: $(docker.token)
            DOCKER_USER: $(docker.user)
        - script: docker image push rlguzman/devops:$(BUILD_NAME)
          env:
            BUILD_NAME: $(Build.DefinitionName)
