name: $(date:yyyyMMdd)$(rev:.rr) #20191209.00

trigger:    # trigger the build when there is new code on master
  - master 

stages:
  - stage: compile 
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              dotnet build 3_devops/Devops.sln
  - stage: test
    jobs:
    - job: aspnet_test
      pool:
        vmImage: ubuntu-18.04
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: test
            projects: 3_devops/Devops.sln
            arguments: --collect:"XPlat Code Coverage"