FROM mcr.microsoft.com/dotnet/core/sdk as build
WORKDIR /aspnet
COPY . .
RUN dotnet build 
RUN dotnet publish --no-restore -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet
WORKDIR /dist
COPY --from=build /aspnet/out .
# EXPOSE 5000
# ENV ASPNETCORE_URLS=http://*:5000
CMD [ "dotnet", "Devops.Client.dll" ]

